# Setup
title: AppBox
tagline: AppBox - Build and Deploy Development iOS Apps Wireless Installation
baseurl: tryappbox.github.io

# About/contact
author: 
name: vineetchoudhary

#Others
markdown: kramdown

theme: jekyll-theme-cayman
